    name: backup-notion

    on:
      push:
      schedule:
        - cron: "0 0 * * *" # 每天零点备份一次
    jobs:
      backup-notion:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: "17"
          - run: npm install
          - name: build script
            run: npm run build
            continue-on-error: true
          - run: npm run run-backup ${{ secrets.NOTION_PAGE_IDS }} ${{ secrets.NOTION_TOKEN }}
          - name: backup as artifact
            uses: actions/upload-artifact@v3
            with: 
              name: notion-backup-zip
              path: backupZip
